### ISSUE TITLE
Improve Custom Climate Portraits Notebook

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/PAVICS-e2e-workflow-tests#32] opened 2020-01-09 19:23 UTC
@aulemahal I pushed my latest changes to the following branch https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/custom_climate_portraits 

We can start from there and see what we can add in terms of:

- Code clean up 
- Map with data
- Summary table
- Uploading of shapefile/GeoJSON to define user regions

Idea is to offer info as in the climateportraits site but more flexibility

**Comment by tlvu** [comment] 2020-01-09 19:31
I assume the notebook will eventually be in pavics-sdi repo?

We are keeping it here for close proximity with the matching changes with the docker image.

The notebook and all the test datas will be deleted here once this branch merge to `master`?

I'd suggest creating a new branch with only the final docker changes so the notebook and all the test datas will never be in history of `master`.

**Comment by tlogan2000** [comment] 2020-01-09 19:39
@tlvu yes I think we want to nail down all the addtions to the docker then will move to pavics-sdi.  I think we will not want to run nightly on your jenkins..  will discuss with you when time comes how best to add it to pavics-sdi
 
Test data not really critical when deployed operationally...  just speeds things up when testing the graphing / climate indicator callbacks etc

**Comment by tlogan2000** [comment] 2020-01-09 19:40
@tlvu I can't seem to assign @aulemahal to this ... can you do it on your end? thx

**Comment by aulemahal** [comment] 2020-01-10 01:29
@tlogan2000 @tlvu  When I run `sudo ./launchnotebook 8888` and then open the notebook in my browser. It cannot run, failing with:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-758d00554569> in <module>
      4 import glob
      5 import ipywidgets as widgets
----> 6 import ipython_blocking
      7 from ipywidgets import FloatSlider, BoundedFloatText, BoundedIntText,HBox, VBox, AppLayout
      8 from IPython.display import HTML, Javascript, display, display_markdown

ModuleNotFoundError: No module named 'ipython_blocking'
```

Am I doing something wrong?

**Comment by tlvu** [comment] 2020-01-10 13:32
@aulemahal You are not using Travis image and you do not need sudo :D

Add your user to group docker: `usermod -a -G docker $USER` so you do not need sudo.

Logout of your windows manager session and log back in for that change to be effective.

Verify your user is effectively in the group docker: `id`, should see `docker` in the list of extra groups.

Start jupyter using Travis image: `DOCKER_IMAGE="pavics/workflow-tests:devel" ./launchnotebook [port]`, doc: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests#start-jupyter-notebook-to-test-a-local-docker-image-build

**Comment by tlvu** [comment] 2020-01-10 14:23
By the way, if Travis make a change to the Jupyter environment (the docker image), it'll take at least 1 hour to build on DockerHub, check here https://hub.docker.com/r/pavics/workflow-tests/tags to see if the new build is available, then `docker pull pavics/workflow-tests:devel` to download it locally.

On the other hand, if you need to make change to the Jupyter env, you can build the docker image locally for testing following https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests#build-the-docker-image-locally-for-testing-a-new-version

Once you commit and push on the `custom_climate_portraits` branch, DockerHub will build and make it available.

**Comment by tlvu** [comment] 2020-01-10 14:25
Forgot to say, that `pavics/workflow-tests` docker image is the same on the Jupyter of PAVICS and also the same used to run integration tests on Jenkins.  This make sure the runtime environment is 100% reproducible.

**Comment by tlvu** [comment] 2022-12-14 23:49
@tlogan2000 @aulemahal Since we closed and deleted branch https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/35, should we also close this issue?

**Closed** 2022-12-16 14:32 UTC
